### ISSUE TITLE
Error when trying to use with CLI

### ISSUE THREAD

**Issue by VagyokC4** [Vheissu/aurelia-google-maps#36]
I'm getting the following error:

```
vendor-bundle.js:3790 GET http://localhost:64713/src/aurelia-google-maps.js g.load @ vendor-bundle.js:3790load @ vendor-bundle.js:3785load @ vendor-bundle.js:3773fetch @ vendor-bundle.js:3773check @ vendor-bundle.js:3773enable @ vendor-bundle.js:3779enable @ vendor-bundle.js:3783(anonymous function) @ vendor-bundle.js:3778(anonymous function) @ vendor-bundle.js:3763y @ vendor-bundle.js:3762enable @ vendor-bundle.js:3777init @ vendor-bundle.js:3772(anonymous function) @ vendor-bundle.js:3782
vendor-bundle.js:1399 Unhandled rejection Error: Script error for "aurelia-google-maps"
http://requirejs.org/docs/errors.html#scripterror
    at Error (native)
    at F (http://localhost:64713/scripts/vendor-bundle.js:3763:290)
    at HTMLScriptElement.onScriptError (http://localhost:64713/scripts/vendor-bundle.js:3786:113)
From previous event:
    at DefaultLoader.loadModule (http://localhost:64713/scripts/vendor-bundle.js:12234:14)
    at _loadPlugin (http://localhost:64713/scripts/vendor-bundle.js:9568:21)
    at http://localhost:64713/scripts/vendor-bundle.js:9561:16
From previous event:
    at loadPlugin (http://localhost:64713/scripts/vendor-bundle.js:9560:75)
    at next (http://localhost:64713/scripts/vendor-bundle.js:9821:20)
From previous event:
    at next (http://localhost:64713/scripts/vendor-bundle.js:9821:56)
    at http://localhost:64713/scripts/vendor-bundle.js:9828:16
From previous event:
    at FrameworkConfiguration.apply (http://localhost:64713/scripts/vendor-bundle.js:9813:44)
    at Aurelia.start (http://localhost:64713/scripts/vendor-bundle.js:9430:23)
    at Object.configure (http://localhost:64713/scripts/app-bundle.js:341:17)
    at http://localhost:64713/scripts/vendor-bundle.js:9250:29
From previous event:
    at config (http://localhost:64713/scripts/vendor-bundle.js:9249:48)
    at handleApp (http://localhost:64713/scripts/vendor-bundle.js:9240:12)
    at http://localhost:64713/scripts/vendor-bundle.js:9269:13
From previous event:
    at http://localhost:64713/scripts/vendor-bundle.js:9267:40
From previous event:
    at http://localhost:64713/scripts/vendor-bundle.js:9266:29
From previous event:
    at run (http://localhost:64713/scripts/vendor-bundle.js:9262:26)
    at Object.<anonymous> (http://localhost:64713/scripts/vendor-bundle.js:9289:3)
    at Object.execCb (http://localhost:64713/scripts/vendor-bundle.js:3785:299)
    at Object.check (http://localhost:64713/scripts/vendor-bundle.js:3774:50)
    at Object.enable (http://localhost:64713/scripts/vendor-bundle.js:3779:58)
    at Object.enable (http://localhost:64713/scripts/vendor-bundle.js:3783:433)
    at Object.<anonymous> (http://localhost:64713/scripts/vendor-bundle.js:3778:436)
    at http://localhost:64713/scripts/vendor-bundle.js:3763:140
    at y (http://localhost:64713/scripts/vendor-bundle.js:3762:207)
    at Object.enable (http://localhost:64713/scripts/vendor-bundle.js:3777:469)
    at Object.init (http://localhost:64713/scripts/vendor-bundle.js:3772:154)
    at http://localhost:64713/scripts/vendor-bundle.js:3782:308
```

UPDATE: I added the following to my aurelia.json file

```
          {
            "name": "aurelia-google-maps",
            "path": "../node_modules/aurelia-google-maps/dist/amd",
            "main": "index"
          },
```

Now I get this error:

```
vendor-bundle.js:11976 Uncaught TypeError: Cannot read property '__useDefault' of undefinedensureOriginOnExports @ vendor-bundle.js:11976(anonymous function) @ vendor-bundle.js:12084execCb @ vendor-bundle.js:3785check @ vendor-bundle.js:3774enable @ vendor-bundle.js:3779init @ vendor-bundle.js:3772(anonymous function) @ vendor-bundle.js:3782
```

**Comment by ghost** [comment]
I am also seeing this issue.

**Comment by cjp666** [comment]
I am also seeing this, anyone figured out what the problem is?

**Comment by cjp666** [comment]
OK figured it for me.  I changed my aurelia.json which was the same as yours to

```
   {
      "name": "aurelia-google-maps",
      "path": "../node_modules/aurelia-google-maps/dist/commonjs",
      "main": "index"
   }
```

**Comment by jasonhjohnson** [comment]
@cjp666 I tried this and I'm getting an `h.load is not a function` error with the CLI. Any ideas?

**Comment by br-gailitis** [comment]
This will not work with stubs enabled.  Set "stub" to false in your aurelia.json.

```
"loader": {
  "type": "require",
  "configTarget": "vendor-bundle.js",
  "includeBundleMetadataInConfig": "auto",
  "plugins": [
    {
      "name": "text",
      "extensions": [
        ".html",
        ".css"
      ],
      "stub": false
    }
  ]
}
```

In addition to this, you will run into issues with resources not being attached to the vendor bundle so you'll also need to add them to the dependency:

```
{
  "name": "aurelia-google-maps",
  "path": "../node_modules/aurelia-google-maps/dist/commonjs",
  "main": "index",
  "resources": [
    "google-maps.html",
    "maps.css"
  ]
}
```

**Comment by Vheissu** [comment]
Instructions for usage with Aurelia CLI were added, they pretty much resemble the comment above except I recommend using the `amd` version, not `commonjs`.
