### ISSUE TITLE
Getting `TypeError: Cannot read property 'then' of null at GoogleMaps.longitudeChanged`

### ISSUE THREAD

**Issue by egeland** [Vheissu/aurelia-google-maps#5]
Hi, I'm getting this error if I navigate away from and then back to the page with the map, not too sure what's happening:

```
ERROR [app-router] TypeError: Cannot read property 'then' of null
    at GoogleMaps.longitudeChanged (http://localhost:9000/jspm_packages/npm/aurelia-google-maps@1.0.4/google-maps.js:275:32)
    at BehaviorPropertyObserver.selfSubscriber (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:3076:48)
    at BehaviorPropertyObserver.call (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2944:14)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2810:18)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:922:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2830:19)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:922:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2830:19)
    at Controller.automate (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2776:12)
    at RouterView.swap (http://localhost:9000/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.2.0/router-view.js:177:38)
```

**Comment by fonckj** [comment]
Similar error here, when navigating back to page containing maps control. 

```
ERROR [app-router] TypeError: Cannot read property 'then' of null
    at GoogleMaps.zoomChanged (http://localhost:9506/jspm_packages/npm/aurelia-google-maps@1.0.5/google-maps.js:306:32)
    at BehaviorPropertyObserver.selfSubscriber (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:3076:48)
    at BehaviorPropertyObserver.call (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2944:14)
    at Controller.bind (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2810:18)
    at View.bind (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:922:24)
    at Controller.bind (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2830:19)
    at Controller.automate (http://localhost:9506/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.1/aurelia-templating.js:2776:12)
    at RouterView.swap (http://localhost:9506/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.2.0/router-view.js:177:38)
    at http://localhost:9506/jspm_packages/npm/aurelia-router@1.0.0-beta.1.2.0/aurelia-router.js:358:29
    at Array.forEach (native)
```

**Comment by ostyn** [comment]
@fonckj, ditto for me.

**Comment by Vheissu** [comment]
This is fixed via a PR which I'll be releasing from @tomtomau

**Comment by Vheissu** [comment]
Latest release is out now.

**Comment by fonckj** [comment]
Solved. Many Thanks!

Jochen
